# Generated by Django 4.0.3 on 2023-06-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_appointment_options_alter_automobilevo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technician',
            options={'ordering': ['last_name', 'last_name']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='created', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vin',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vip',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
